### ISSUE TITLE
examples/data_for_nerf.pkl missing

### ISSUE THREAD

**Issue by owlshrimp** [brandontrabucco/nerf#1]
Hi,

When running train_conditional_nerf.py in a suitable environment, examples/data_for_nerf.pkl cannot be found.

Is there some way to run this code with the data downloaded by https://github.com/bmild/nerf/blob/master/download_example_data.sh perhaps?

Thanks

**Comment by brandontrabucco** [comment]
Hi Matt, I didn't mean to push this training script, please refer to the example jupyter notebook once I update it!
